db:
  container_name: mysql-test
  image: mysql
  restart: always
  net: "host"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: demo
  volumes:
    - ./migrations:/docker-entrypoint-initdb.d

rabbit_mq:
  container_name: rabbit_mq-test
  image: "rabbitmq:3-management"
  restart: always
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  net: "host"
  ports:
    - "15672:15672"
    - "5672:5672"

php:
  container_name: php-test
  build: .
  restart: always
  #stdin_open: true
  #tty: true
  command: bin/console rabbitmq:consumer user_balance_transaction
  net: "host"
  ports:
    - "10111:10111"
  environment:
    PHP_IDE_CONFIG: "serverName=IqOption"
  volumes:
    - ./:/var/www/iq_option
    - ./php.ini:/etc/opt/remi/php71/php.d/99.ini:ro
  working_dir: /var/www/iq_option