services:
    repository.user_balance_transaction:
        class: AppBundle\Entity\Repository\UserBalanceTransactionRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle\Entity\UserBalanceTransaction']